Repository entropicalabs/openqaoa, pull requests merged in 2022-11, with the labels that each got.

#89 New Traveling Salesman QUBO Formulation
  .github/workflows/test_dev.yml
  .readthedocs.yml
  docs/requirements.txt
  docs/source/problems.rst
  openqaoa/problems/problem.py
  tests/test_problems.py
Labels: bug, enhancement

#113 Fixing the docs
  .github/images/Entropica_logo.png
  .github/workflows/test_dev.yml
  .readthedocs.yml
  docs/Makefile
  docs/notebook_converter.sh
  docs/source/conf.py
  docs/source/index.rst
  docs/source/optimizers.rst
  docs/source/problems.rst
  docs/source/qaoaparameters.rst
  docs/source/rqaoa.rst
  docs/source/workflows.rst
  examples/01_workflows_example.ipynb
  examples/02_simulators_comparison.ipynb
  examples/03_qaoa_on_qpus.ipynb
  examples/04_qaoa_variational_parameters.ipynb
  examples/05_advanced_parameterization.ipynb
  examples/06_fast_qaoa_simulator.ipynb
  examples/07_cost_landscapes_w_manual_mode.ipynb
  examples/08_results_example.ipynb
  examples/09_RQAOA_example.ipynb
  examples/10_workflows_on_Amazon_braket.ipynb
  openqaoa/backends/simulators/qaoa_vectorized.py
  openqaoa/derivative_functions.py
  openqaoa/devices.py
  openqaoa/optimizers/training_vqa.py
  openqaoa/problems/problem.py
  openqaoa/qaoa_parameters/annealingparams.py
  openqaoa/qaoa_parameters/fourierparams.py
  openqaoa/qaoa_parameters/standardparams.py
  openqaoa/qfim.py
  openqaoa/utilities.py
  openqaoa/workflows/optimizer.py
  openqaoa/workflows/parameters/qaoa_parameters.py
Labels: bug, documentation

#109 RQAOA workflow
  docs/source/logger_and_results.rst
  docs/source/rqaoa.rst
  docs/source/workflows.rst
  examples/09_RQAOA_example.ipynb
  openqaoa/rqaoa/rqaoa.py
  openqaoa/rqaoa/rqaoa_results.py
  openqaoa/workflows/optimizer.py
  openqaoa/workflows/parameters/rqaoa_parameters.py
  tests/test_results.py
  tests/test_rqaoa.py
  tests/test_workflows.py
Labels: enhancement

#121 Use sparse.linalg.expm for exponentiation of sparse matrices (for sci…
  openqaoa/backends/simulators/qaoa_vectorized.py
  setup.py
Labels: bug

#120 Update setup
  README.md
  runtime.txt
  setup.py
Labels: dependencies

#108 Bugfix: QPU qubit overflow
  openqaoa/backends/qpus/qaoa_braket_qpu.py
  openqaoa/backends/qpus/qaoa_pyquil_qpu.py
  openqaoa/backends/qpus/qaoa_qiskit_qpu.py
  openqaoa/devices.py
  openqaoa/optimizers/training_vqa.py
  tests/test_optimizers.py
  tests/test_pyquil_qvm.py
  tests/test_qpu_braket.py
  tests/test_qpu_qiskit.py
Labels: bug

#85 Alternating Ansatz Feature
  docs/source/index.rst
  examples/04_qaoa_variational_parameters.ipynb
  examples/11_Mixer_example.ipynb
  openqaoa/qaoa_parameters/baseparams.py
  openqaoa/qaoa_parameters/extendedparams.py
  openqaoa/qaoa_parameters/fourierparams.py
  openqaoa/qaoa_parameters/gatemap.py
  openqaoa/qaoa_parameters/hamiltonianmapper.py
  openqaoa/utilities.py
  tests/test_parameters.py
  tests/test_parameters_plots.py
  tests/test_qpu_qiskit.py
  tests/test_workflows.py
Labels: enhancement

#101 Implementation of pennylane optimizers
  docs/requirements.txt
  docs/source/optimizers.rst
  openqaoa/optimizers/__init__.py
  openqaoa/optimizers/pennylane/NOTICE
  openqaoa/optimizers/pennylane/__init__.py
  openqaoa/optimizers/pennylane/fourier/__init__.py
  openqaoa/optimizers/pennylane/fourier/reconstruct.py
  openqaoa/optimizers/pennylane/math/__init__.py
  openqaoa/optimizers/pennylane/math/is_independent.py
  openqaoa/optimizers/pennylane/math/matrix_manipulation.py
  openqaoa/optimizers/pennylane/math/multi_dispatch.py
  openqaoa/optimizers/pennylane/math/quantum.py
  openqaoa/optimizers/pennylane/math/single_dispatch.py
  openqaoa/optimizers/pennylane/math/utils.py
  openqaoa/optimizers/pennylane/numpy/__init__.py
  openqaoa/optimizers/pennylane/numpy/fft.py
  openqaoa/optimizers/pennylane/numpy/linalg.py
  openqaoa/optimizers/pennylane/numpy/random.py
  openqaoa/optimizers/pennylane/numpy/tensor.py
  openqaoa/optimizers/pennylane/numpy/wrapper.py
  openqaoa/optimizers/pennylane/optimization_methods_pennylane.py
  openqaoa/optimizers/pennylane/pennylane_optimizers/adagrad.py
  openqaoa/optimizers/pennylane/pennylane_optimizers/adam.py
  openqaoa/optimizers/pennylane/pennylane_optimizers/gradient_descent.py
  openqaoa/optimizers/pennylane/pennylane_optimizers/momentum.py
  openqaoa/optimizers/pennylane/pennylane_optimizers/nesterov_momentum.py
  openqaoa/optimizers/pennylane/pennylane_optimizers/rms_prop.py
  openqaoa/optimizers/pennylane/pennylane_optimizers/rotosolve.py
  openqaoa/optimizers/pennylane/pennylane_optimizers/spsa.py
  openqaoa/optimizers/qaoa_optimizer.py
  openqaoa/optimizers/training_vqa.py
  openqaoa/workflows/parameters/qaoa_parameters.py
  setup.py
  tests/test_optimizers_pennylane.py
  tests/test_workflows.py
Labels: enhancement
