Repository entropicalabs/openqaoa, pull requests merged in 2022-10, with the labels that each got.

#86 Adding a constant value of linear_ramp_tim
  examples/5_advanced_parameterization.ipynb
Labels: documentation

#82 added plot_probabilities method in result class
  openqaoa/optimizers/result.py
  tests/test_result_object.py
Labels: enhancement

#88 fixed varational params plot method
  openqaoa/qaoa_parameters/annealingparams.py
  openqaoa/qaoa_parameters/baseparams.py
  openqaoa/qaoa_parameters/extendedparams.py
  openqaoa/qaoa_parameters/fourierparams.py
  openqaoa/qaoa_parameters/standardparams.py
  tests/test_parameters_plots.py
Labels: bug

#90 Add Docplex tutorials
  examples/community_tutorials/01_tutorial_quantum_approximate_optimization_algorithm.ipynb
  examples/community_tutorials/02_docplex_example.ipynb
  examples/community_tutorials/03_portfolio_optimization.ipynb
  examples/community_tutorials/04_binpacking.ipynb
  setup.py
  tests/test_notebooks.py
Labels: documentation

#117 Dev
  examples/community_tutorials/01_tutorial_quantum_approximate_optimization_algorithm.ipynb
  examples/community_tutorials/02_docplex_example.ipynb
  examples/community_tutorials/03_portfolio_optimization.ipynb
  examples/community_tutorials/04_binpacking.ipynb
  examples/community_tutorials/mvc_examples/bipartite_graphs.ipynb
  examples/community_tutorials/mvc_examples/problems/bipartite_graph7x7_test1.json
  examples/community_tutorials/mvc_examples/problems/bipartite_graph7x7_test2.json
  examples/community_tutorials/mvc_examples/problems/bipartite_graph7x7_test3.json
  examples/community_tutorials/mvc_examples/problems/bipartite_graph7x9_test1.json
  examples/community_tutorials/mvc_examples/problems/bipartite_graph7x9_test2.json
  examples/community_tutorials/mvc_examples/problems/bipartite_graph7x9_test3.json
  examples/community_tutorials/mvc_examples/problems/bipartite_graph8x8_test1.json
  examples/community_tutorials/mvc_examples/problems/bipartite_graph8x8_test2.json
  examples/community_tutorials/mvc_examples/problems/bipartite_graph9x9_test1.json
  examples/community_tutorials/mvc_examples/problems/bipartite_graph9x9_test2.json
  openqaoa/backends/qpus/qaoa_pyquil_qpu.py
  openqaoa/optimizers/training_vqa.py
  openqaoa/workflows/optimizer.py
  openqaoa/workflows/parameters/qaoa_parameters.py
  setup.py
  tests/test_notebooks.py
Labels: bug, documentation
