Repository entropicalabs/openqaoa, pull requests merged in 2023-01, with the labels that each got.

#152 Metadata for Problem objects
  examples/community_tutorials/02_docplex_example.ipynb
  openqaoa/problems/problem.py
  openqaoa/utilities.py
  tests/test_problems.py
Labels: enhancement

#165 QUBO / Problem from dict
  openqaoa/problems/problem.py
  tests/test_problems.py
Labels: enhancement

#157 Bug fix for isolated nodes when running RQAOA
  openqaoa/rqaoa/rqaoa.py
  openqaoa/workflows/optimizer.py
  tests/test_rqaoa.py
Labels: bug

#166 Changing data saving workflows methods
  openqaoa/optimizers/result.py
  openqaoa/rqaoa/rqaoa_results.py
  openqaoa/workflows/optimizer.py
  tests/test_workflows.py
Labels: enhancement

#158 Bugfix vanishing instances after elimination
  openqaoa/rqaoa/rqaoa.py
  openqaoa/workflows/optimizer.py
  tests/test_rqaoa.py
Labels: bug

#164 Changed folder structure and access to problems module.
  docs/source/problems.rst
  examples/01_workflows_example.ipynb
  examples/02_simulators_comparison.ipynb
  examples/03_qaoa_on_qpus.ipynb
  examples/05_advanced_parameterization.ipynb
  examples/06_fast_qaoa_simulator.ipynb
  examples/08_results_example.ipynb
  examples/09_RQAOA_example.ipynb
  examples/10_workflows_on_Amazon_braket.ipynb
  examples/11_Mixer_example.ipynb
  examples/X_dumping_data.ipynb
  examples/community_tutorials/01_tutorial_quantum_approximate_optimization_algorithm.ipynb
  examples/community_tutorials/02_docplex_example.ipynb
  examples/community_tutorials/mvc_examples/bipartite_graphs.ipynb
  openqaoa/problems/__init__.py
  openqaoa/problems/converters.py
  openqaoa/problems/helper_functions.py
  openqaoa/problems/knapsack.py
  openqaoa/problems/maximumcut.py
  openqaoa/problems/minimumvertexcover.py
  openqaoa/problems/numberpartition.py
  openqaoa/problems/problem.py
  openqaoa/problems/qubo.py
  openqaoa/problems/shortestpath.py
  openqaoa/problems/tsp.py
  openqaoa/rqaoa/rqaoa.py
  openqaoa/utilities.py
  openqaoa/workflows/optimizer.py
  tests/test_converters.py
  tests/test_optimizers_pennylane.py
  tests/test_parameters_plots.py
  tests/test_problems.py
  tests/test_pyquil_qvm.py
  tests/test_qpu_braket.py
  tests/test_qpu_qiskit.py
  tests/test_result_object.py
  tests/test_results.py
  tests/test_rqaoa.py
  tests/test_simulators.py
  tests/test_utilities.py
  tests/test_workflows.py
Labels: refactor

#168 Better elimination_rules keys
  examples/01_workflows_example.ipynb
  examples/02_simulators_comparison.ipynb
  examples/03_qaoa_on_qpus.ipynb
  examples/04_qaoa_variational_parameters.ipynb
  examples/05_advanced_parameterization.ipynb
  examples/06_fast_qaoa_simulator.ipynb
  examples/07_cost_landscapes_w_manual_mode.ipynb
  examples/08_results_example.ipynb
  examples/09_RQAOA_example.ipynb
  examples/10_workflows_on_Amazon_braket.ipynb
  examples/11_Mixer_example.ipynb
  openqaoa/rqaoa/rqaoa.py
  openqaoa/workflows/optimizer.py
  tests/test_results.py
  tests/test_rqaoa.py
  tests/test_workflows.py
Labels: bug

#124 Implementation of shot adaptative optimizers
  openqaoa/backends/qpus/qaoa_braket_qpu.py
  openqaoa/backends/qpus/qaoa_pyquil_qpu.py
  openqaoa/backends/qpus/qaoa_qiskit_qpu.py
  openqaoa/backends/simulators/qaoa_qiskit_sim.py
  openqaoa/basebackend.py
  openqaoa/derivative_functions.py
  openqaoa/optimizers/optimization_methods.py
  openqaoa/optimizers/pennylane/optimization_methods_pennylane.py
  openqaoa/optimizers/qaoa_optimizer.py
  openqaoa/optimizers/result.py
  openqaoa/optimizers/training_vqa.py
  tests/test_backends.py
  tests/test_derivative.py
  tests/test_optimizers.py
  tests/test_optimizers_pennylane.py
  tests/test_result_object.py
  tests/test_results.py
Labels: enhancement

#147 Implementing the analytical formula for p=1 as a backened
  docs/source/backends.rst
  openqaoa/backends/__init__.py
  openqaoa/backends/qaoa_backend.py
  openqaoa/backends/simulators/qaoa_analytical_sim.py
  openqaoa/backends/simulators/qaoa_pyquil_sim.py
  openqaoa/backends/simulators/qaoa_qiskit_sim.py
  openqaoa/backends/simulators/qaoa_vectorized.py
  openqaoa/basebackend.py
  openqaoa/devices.py
  openqaoa/optimizers/result.py
  openqaoa/optimizers/training_vqa.py
  openqaoa/qaoa_parameters/baseparams.py
  openqaoa/utilities.py
  openqaoa/workflows/optimizer.py
  tests/test_analytical_simulator.py
  tests/test_backends.py
  tests/test_derivative.py
Labels: enhancement
